"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Language } from "@/lib/i18n";
import { useItAccess } from "@/components/layout/app-shell";

type Row={id:string;source:"system"|"manual";tenant_id:string|null;branch_id:string|null;tenant:string;branch:string;device:string;severity:string;code:string;title:string;message:string;detected_at:string;status:string;editable:boolean;deletable:boolean};
type Option={id:string;name:string;code?:string;tenant_id?:string};
type Payload={summary:{total:number;open:number;critical:number;manual:number};rows:Row[];options:{tenants:Option[];branches:Option[]}};
const copy={
 th:{title:"เหตุขัดข้อง",desc:"ค้นหา ติดตาม ปิดเคส และจัดการ Incident ที่ IT สร้างเองได้ โดย Incident จากระบบจะเก็บไว้เป็นหลักฐาน",search:"ค้นหาร้าน สาขา อุปกรณ์ รหัส หรือข้อความ",allSeverity:"ทุกระดับ",allStatus:"ทุกสถานะ",allSource:"ทุกแหล่ง",system:"ระบบ",manual:"IT สร้างเอง",add:"เพิ่ม Incident",refresh:"รีเฟรช",total:"ทั้งหมด",open:"ยังเปิด",critical:"วิกฤต",manualCount:"IT สร้างเอง",severity:"ระดับ",source:"แหล่ง",store:"ร้าน",branch:"สาขา",device:"อุปกรณ์",incident:"Incident",detected:"ตรวจพบ",status:"สถานะ",actions:"จัดการ",edit:"แก้ไข",resolve:"ปิดเคส",reopen:"เปิดใหม่",delete:"ลบ",save:"บันทึก",cancel:"ยกเลิก",titleLabel:"ชื่อเหตุขัดข้อง",message:"รายละเอียด",code:"รหัส",tenant:"ร้านค้า",branchLabel:"สาขา",empty:"ไม่พบ Incident ตามเงื่อนไข",confirmDelete:"ลบ Incident ที่ IT สร้างเองรายการนี้หรือไม่?"},
 en:{title:"Incidents",desc:"Search, track and resolve incidents. System incidents remain immutable evidence while manually created incidents can be managed.",search:"Search store, branch, device, code or text",allSeverity:"All severities",allStatus:"All statuses",allSource:"All sources",system:"System",manual:"Manual",add:"Add Incident",refresh:"Refresh",total:"Total",open:"Open",critical:"Critical",manualCount:"Manual",severity:"Severity",source:"Source",store:"Store",branch:"Branch",device:"Device",incident:"Incident",detected:"Detected",status:"Status",actions:"Actions",edit:"Edit",resolve:"Resolve",reopen:"Reopen",delete:"Delete",save:"Save",cancel:"Cancel",titleLabel:"Title",message:"Details",code:"Code",tenant:"Store",branchLabel:"Branch",empty:"No incidents match the filters",confirmDelete:"Delete this manually created incident?"}
} as const;

function severityLabel(value:string,language:Language){
  if(language==="en")return value;
  return value==="critical"?"วิกฤต":value==="warning"?"เฝ้าระวัง":value==="info"?"ข้อมูล":value;
}
function statusLabel(value:string,language:Language){
  if(language==="en")return value;
  return value==="resolved"?"ปิดแล้ว":value==="investigating"?"กำลังตรวจสอบ":value==="open"?"เปิดอยู่":value;
}

export function ItAdminIncidentsConsole({language}:{language:Language}){
 const t=copy[language]; const access=useItAccess();
 const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [q,setQ]=useState(""); const [severity,setSeverity]=useState(""); const [status,setStatus]=useState(""); const [source,setSource]=useState("");
 const [editing,setEditing]=useState<Row|null|undefined>(undefined);
 const [form,setForm]=useState({tenant_id:"",branch_id:"",severity:"warning",code:"MANUAL",title:"",message:"",status:"open"});
 const load=useCallback(async()=>{setLoading(true);setError("");try{
   const params=new URLSearchParams(); if(q)params.set("q",q); if(severity)params.set("severity",severity); if(status)params.set("status",status); if(source)params.set("source",source);
   const response=await fetch("/api/it-admin/v1/incidents?"+params.toString(),{cache:"no-store"}); const body=await response.json().catch(()=>null) as {data?:Payload;error?:{message?:string}}|null;
   if(!response.ok||!body?.data)throw new Error(body?.error?.message||"Unable to load incidents"); setData(body.data);
 }catch(e){setError(e instanceof Error?e.message:"Unable to load incidents");}finally{setLoading(false);}},[q,severity,status,source]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(timer);},[load]);
 const branches=useMemo(()=> (data?.options.branches??[]).filter(b=>!form.tenant_id||b.tenant_id===form.tenant_id),[data,form.tenant_id]);
 const openNew=()=>{setEditing(null);setForm({tenant_id:"",branch_id:"",severity:"warning",code:"MANUAL",title:"",message:"",status:"open"});};
 const openEdit=(row:Row)=>{setEditing(row);setForm({tenant_id:row.tenant_id||"",branch_id:row.branch_id||"",severity:row.severity,code:row.code,title:row.title,message:row.message,status:row.status});};
 const save=async()=>{const method=editing?"PATCH":"POST";const body=editing?{...form,id:editing.id,source:"manual"}:form;const response=await fetch("/api/it-admin/v1/incidents",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(response.ok){setEditing(undefined);await load();}else{const j=await response.json().catch(()=>null);alert(j?.error?.message||"Save failed");}};
 const changeStatus=async(row:Row,next:string)=>{const response=await fetch("/api/it-admin/v1/incidents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,source:row.source,status:next})});if(response.ok)await load();};
 const remove=async(row:Row)=>{if(!confirm(t.confirmDelete))return;const response=await fetch("/api/it-admin/v1/incidents",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})});if(response.ok)await load();};
 return <div className="grid gap-5">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.18em] text-blue-600">OPERATIONS</div><h2 className="mt-2 text-3xl font-black">{t.title}</h2><p className="mt-2 max-w-3xl text-sm text-slate-600">{t.desc}</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 font-bold">{t.refresh}</button><button onClick={openNew} className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">{t.add}</button></div></header>
  {error?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>:null}
  <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[t.total,data?.summary.total],[t.open,data?.summary.open],[t.critical,data?.summary.critical],[t.manualCount,data?.summary.manual]].map(([label,value])=><article key={String(label)} className="rounded-2xl border bg-white p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-2xl font-black">{value??"—"}</div></article>)}</section>
  <section className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap gap-2 border-b p-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="min-w-[260px] flex-1 rounded-xl border px-3 py-2"/><select value={severity} onChange={e=>setSeverity(e.target.value)} className="rounded-xl border px-3"><option value="">{t.allSeverity}</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3"><option value="">{t.allStatus}</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option></select><select value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl border px-3"><option value="">{t.allSource}</option><option value="system">{t.system}</option><option value="manual">{t.manual}</option></select></div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{[t.severity,t.source,t.store,t.branch,t.device,t.incident,t.detected,t.status,t.actions].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{(data?.rows??[]).map(row=><tr key={row.source+row.id} className="border-t"><td className="px-3 py-3">{severityLabel(row.severity,language)}</td><td className="px-3 py-3">{row.source==="system"?t.system:t.manual}</td><td className="px-3 py-3">{row.tenant}</td><td className="px-3 py-3">{row.branch}</td><td className="px-3 py-3">{row.device}</td><td className="px-3 py-3"><div className="font-bold">{row.title}</div><div className="max-w-[360px] truncate text-xs text-slate-500">{row.code} · {row.message}</div></td><td className="px-3 py-3">{new Date(row.detected_at).toLocaleString(language==="th"?"th-TH":"en-US")}</td><td className="px-3 py-3">{statusLabel(row.status,language)}</td><td className="px-3 py-3"><div className="flex flex-wrap gap-1">{row.editable?<button onClick={()=>openEdit(row)} className="rounded border px-2 py-1">{t.edit}</button>:null}{row.status==="resolved"?<button onClick={()=>void changeStatus(row,"open")} className="rounded border px-2 py-1">{t.reopen}</button>:<button onClick={()=>void changeStatus(row,"resolved")} className="rounded border px-2 py-1">{t.resolve}</button>}{row.deletable&&access.canDelete?<button onClick={()=>void remove(row)} className="rounded border border-red-300 px-2 py-1 text-red-700">{t.delete}</button>:null}</div></td></tr>)}{!loading&&!(data?.rows.length)?<tr><td colSpan={9} className="p-8 text-center text-slate-500">{t.empty}</td></tr>:null}</tbody></table></div></section>
  {editing!==undefined?<div className="fixed inset-0 z-[500] grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-black">{editing?t.edit:t.add}</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm"><span>{t.tenant}</span><select value={form.tenant_id} onChange={e=>setForm({...form,tenant_id:e.target.value,branch_id:""})} className="rounded-xl border px-3 py-2"><option value="">—</option>{data?.options.tenants.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="grid gap-1 text-sm"><span>{t.branchLabel}</span><select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})} className="rounded-xl border px-3 py-2"><option value="">—</option>{branches.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="grid gap-1 text-sm"><span>{t.severity}</span><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} className="rounded-xl border px-3 py-2"><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><label className="grid gap-1 text-sm"><span>{t.code}</span><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="rounded-xl border px-3 py-2"/></label><label className="grid gap-1 text-sm md:col-span-2"><span>{t.titleLabel}</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl border px-3 py-2"/></label><label className="grid gap-1 text-sm md:col-span-2"><span>{t.message}</span><textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows={4} className="rounded-xl border px-3 py-2"/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditing(undefined)} className="rounded-xl border px-4 py-2">{t.cancel}</button><button onClick={()=>void save()} className="rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">{t.save}</button></div></div></div>:null}
 </div>;
}
